[package]
name = "hello_world"
version = "0.1.0"
authors = ["cdetrio <cdetrio@gmail.com>"]

[dependencies]
bn = { git = "https://github.com/paritytech/bn" }
rand = "0.3"
rustc-serialize = "0.3"
num = "0.1"
hex-slice = "0.1.0"
